[package]
name = "quickjs"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasi-common = "10.0.1"
wasmtime = "10.0.1"
wasmtime-wasi = "10.0.1"

[dev-dependencies]
clap = { version = "4.3.10", features = ["derive"] }
num_cpus = "1.16.0"
rayon = "1.7.0"
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false